/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LisaEldridgeImport } from './routes/lisaEldridge'
import { Route as BeautyIconsImport } from './routes/beautyIcons'
import { Route as AdamReedImport } from './routes/adamReed'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const LisaEldridgeRoute = LisaEldridgeImport.update({
  id: '/lisaEldridge',
  path: '/lisaEldridge',
  getParentRoute: () => rootRoute,
} as any)

const BeautyIconsRoute = BeautyIconsImport.update({
  id: '/beautyIcons',
  path: '/beautyIcons',
  getParentRoute: () => rootRoute,
} as any)

const AdamReedRoute = AdamReedImport.update({
  id: '/adamReed',
  path: '/adamReed',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/adamReed': {
      id: '/adamReed'
      path: '/adamReed'
      fullPath: '/adamReed'
      preLoaderRoute: typeof AdamReedImport
      parentRoute: typeof rootRoute
    }
    '/beautyIcons': {
      id: '/beautyIcons'
      path: '/beautyIcons'
      fullPath: '/beautyIcons'
      preLoaderRoute: typeof BeautyIconsImport
      parentRoute: typeof rootRoute
    }
    '/lisaEldridge': {
      id: '/lisaEldridge'
      path: '/lisaEldridge'
      fullPath: '/lisaEldridge'
      preLoaderRoute: typeof LisaEldridgeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adamReed': typeof AdamReedRoute
  '/beautyIcons': typeof BeautyIconsRoute
  '/lisaEldridge': typeof LisaEldridgeRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adamReed': typeof AdamReedRoute
  '/beautyIcons': typeof BeautyIconsRoute
  '/lisaEldridge': typeof LisaEldridgeRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/adamReed': typeof AdamReedRoute
  '/beautyIcons': typeof BeautyIconsRoute
  '/lisaEldridge': typeof LisaEldridgeRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/adamReed' | '/beautyIcons' | '/lisaEldridge'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/adamReed' | '/beautyIcons' | '/lisaEldridge'
  id: '__root__' | '/' | '/adamReed' | '/beautyIcons' | '/lisaEldridge'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdamReedRoute: typeof AdamReedRoute
  BeautyIconsRoute: typeof BeautyIconsRoute
  LisaEldridgeRoute: typeof LisaEldridgeRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdamReedRoute: AdamReedRoute,
  BeautyIconsRoute: BeautyIconsRoute,
  LisaEldridgeRoute: LisaEldridgeRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/adamReed",
        "/beautyIcons",
        "/lisaEldridge"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/adamReed": {
      "filePath": "adamReed.tsx"
    },
    "/beautyIcons": {
      "filePath": "beautyIcons.tsx"
    },
    "/lisaEldridge": {
      "filePath": "lisaEldridge.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
