/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ServicesImport } from './routes/services'
import { Route as PodcastsImport } from './routes/podcasts'
import { Route as LisaEldridgeImport } from './routes/lisaEldridge'
import { Route as FeaturedImport } from './routes/featured'
import { Route as BeautyIconsImport } from './routes/beautyIcons'
import { Route as AdamReedImport } from './routes/adamReed'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ServicesRoute = ServicesImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRoute,
} as any)

const PodcastsRoute = PodcastsImport.update({
  id: '/podcasts',
  path: '/podcasts',
  getParentRoute: () => rootRoute,
} as any)

const LisaEldridgeRoute = LisaEldridgeImport.update({
  id: '/lisaEldridge',
  path: '/lisaEldridge',
  getParentRoute: () => rootRoute,
} as any)

const FeaturedRoute = FeaturedImport.update({
  id: '/featured',
  path: '/featured',
  getParentRoute: () => rootRoute,
} as any)

const BeautyIconsRoute = BeautyIconsImport.update({
  id: '/beautyIcons',
  path: '/beautyIcons',
  getParentRoute: () => rootRoute,
} as any)

const AdamReedRoute = AdamReedImport.update({
  id: '/adamReed',
  path: '/adamReed',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/adamReed': {
      id: '/adamReed'
      path: '/adamReed'
      fullPath: '/adamReed'
      preLoaderRoute: typeof AdamReedImport
      parentRoute: typeof rootRoute
    }
    '/beautyIcons': {
      id: '/beautyIcons'
      path: '/beautyIcons'
      fullPath: '/beautyIcons'
      preLoaderRoute: typeof BeautyIconsImport
      parentRoute: typeof rootRoute
    }
    '/featured': {
      id: '/featured'
      path: '/featured'
      fullPath: '/featured'
      preLoaderRoute: typeof FeaturedImport
      parentRoute: typeof rootRoute
    }
    '/lisaEldridge': {
      id: '/lisaEldridge'
      path: '/lisaEldridge'
      fullPath: '/lisaEldridge'
      preLoaderRoute: typeof LisaEldridgeImport
      parentRoute: typeof rootRoute
    }
    '/podcasts': {
      id: '/podcasts'
      path: '/podcasts'
      fullPath: '/podcasts'
      preLoaderRoute: typeof PodcastsImport
      parentRoute: typeof rootRoute
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adamReed': typeof AdamReedRoute
  '/beautyIcons': typeof BeautyIconsRoute
  '/featured': typeof FeaturedRoute
  '/lisaEldridge': typeof LisaEldridgeRoute
  '/podcasts': typeof PodcastsRoute
  '/services': typeof ServicesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adamReed': typeof AdamReedRoute
  '/beautyIcons': typeof BeautyIconsRoute
  '/featured': typeof FeaturedRoute
  '/lisaEldridge': typeof LisaEldridgeRoute
  '/podcasts': typeof PodcastsRoute
  '/services': typeof ServicesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/adamReed': typeof AdamReedRoute
  '/beautyIcons': typeof BeautyIconsRoute
  '/featured': typeof FeaturedRoute
  '/lisaEldridge': typeof LisaEldridgeRoute
  '/podcasts': typeof PodcastsRoute
  '/services': typeof ServicesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adamReed'
    | '/beautyIcons'
    | '/featured'
    | '/lisaEldridge'
    | '/podcasts'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adamReed'
    | '/beautyIcons'
    | '/featured'
    | '/lisaEldridge'
    | '/podcasts'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/adamReed'
    | '/beautyIcons'
    | '/featured'
    | '/lisaEldridge'
    | '/podcasts'
    | '/services'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdamReedRoute: typeof AdamReedRoute
  BeautyIconsRoute: typeof BeautyIconsRoute
  FeaturedRoute: typeof FeaturedRoute
  LisaEldridgeRoute: typeof LisaEldridgeRoute
  PodcastsRoute: typeof PodcastsRoute
  ServicesRoute: typeof ServicesRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdamReedRoute: AdamReedRoute,
  BeautyIconsRoute: BeautyIconsRoute,
  FeaturedRoute: FeaturedRoute,
  LisaEldridgeRoute: LisaEldridgeRoute,
  PodcastsRoute: PodcastsRoute,
  ServicesRoute: ServicesRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/adamReed",
        "/beautyIcons",
        "/featured",
        "/lisaEldridge",
        "/podcasts",
        "/services"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/adamReed": {
      "filePath": "adamReed.tsx"
    },
    "/beautyIcons": {
      "filePath": "beautyIcons.tsx"
    },
    "/featured": {
      "filePath": "featured.tsx"
    },
    "/lisaEldridge": {
      "filePath": "lisaEldridge.tsx"
    },
    "/podcasts": {
      "filePath": "podcasts.tsx"
    },
    "/services": {
      "filePath": "services.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
